spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        jdbc.time_zone: UTC

  jackson:
    serialization:
      INDENT_OUTPUT: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

server:
  port: 9090
  servlet:
    context-path: /auth
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
    spring:
  main:
    web-application-type: reactive

eureka:
    client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
    defaultZone: http://localhost:8761/eureka
    

jwt:
  secret: "your-super-secret-key-at-least-32-chars"
  expiration-ms: 86400000 # 1 day in milliseconds
  
rbac-service:
  base-url: http://localhost:8080/rbac





    
